build: off

cache:
    - C:\strawberry

install:
  - if not exist "C:\strawberry" cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cpanm YAML::Tiny
#install:
#  - echo "hello world"
#  - ps: Invoke-WebRequest -Uri http://strawberryperl.com/download/5.26.1.1/strawberry-perl-5.26.1.1-64bit.msi -OutFile strawberry-perl-64bit.msi
#  - ps: Start-Process msiexec.exe -ArgumentList @("/package", "strawberry-perl-64bit.msi", "/qn", "INSTALLDIR=C:\strawberry") -Wait
#  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
#  - cpanm YAML::Tiny
#  - small-test.bat
