# appveyor.yml settings
#   reference: http://blogs.perl.org/users/eserte/2016/04/testing-with-appveyor.html
build: off

cache:
    - C:\strawberry

# all the perl stuff
install:
  - if not exist "C:\strawberry" cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cpanm YAML::Tiny
  - cpanm File::HomeDir
  - cpanm Unicode::GCString
  - cpanm --installdeps Log::Log4perl
  - cpanm --force Log::Log4perl
  - cpanm Log::Dispatch::File

# the test cases
build_script:
  - cd test-cases/travis-ci
  - appveyor-test-cases.bat
