language: bash
before_install:
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - curl -L http://cpanmin.us | perl - App::cpanminus
  - cpanm YAML::Tiny
  - cpanm File::HomeDir
  - cpanm Unicode::GCString
  - cpanm Log::Log4perl
  - cpanm Log::Dispatch::File
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
script: bash ./hello-world.sh
